import type { UserEntry } from '@/app/profile/UserEntriesTable';
import type { ArtistLatestItem } from '@/lib/artist/artistLatest';

export type ProfileSummary = { totalContributions: number; approved: number; selfEdits: number; artistsAdded: number; pending: number; entries: UserEntry[] };
export type ProfileArtist = {artistId: string; artistName: string; imageUrl: string | null};
export type ProfileArtistsPage = {artists: ProfileArtist[]; total: number; next: number | null};
export type ProfileUpdate = ArtistLatestItem & { artistId: string; artistName: string };
export type LiveProfileModel = ProfileSummary & {
  name: string;
  photo: string | null;
  artists: ProfileArtist[];
  artistTotal: number;
  artistMatches: ProfileArtist[];
  matchesTotal: number;
  artistsLoading: boolean;
  artistsError: string | null;
  matchesLoading: boolean;
  matchesError: string | null;
  hasMoreArtists: boolean;
  hasMoreMatches: boolean;
  loadMoreArtists: () => void;
  loadMoreMatches: () => void;
  setArtistSearch: (query: string) => void;
  setUpdateFilter: (value: string) => void;
  updates: ProfileUpdate[];
  updatesLoading: boolean;
  updatesError: string | null;
  updatesUnavailable: boolean;
  checkedArtists: number;
  hasMoreUpdates: boolean;
  loadMoreUpdates: () => void;
  saveProfile: (name: string, photo: File | null) => Promise<{ name: string; photo: string | null }>;
};
