-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."platform_type" AS ENUM('social', 'web3', 'listen');--> statement-breakpoint
CREATE TABLE "funfacts" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "funfacts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lore_drop" text,
	"behind_the_scenes" text,
	"recent_activity" text,
	"surprise_me" text NOT NULL,
	"is_active" boolean DEFAULT false
);
--> statement-breakpoint
ALTER TABLE "funfacts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "aiprompts" (
	"prompt_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp,
	"prompt_before_name" text,
	"is_active" boolean DEFAULT false NOT NULL,
	"prompt_after_name" text
);
--> statement-breakpoint
ALTER TABLE "aiprompts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "history" (
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"posted_at" timestamp with time zone NOT NULL,
	"top_artist" text,
	"top_track" text,
	"track_id" text
);
--> statement-breakpoint
ALTER TABLE "history" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "bot_prompts" (
	"slow" jsonb NOT NULL,
	"moderate" jsonb,
	"busy" jsonb,
	"prompts" text NOT NULL,
	"fun_fact" text,
	"shaming" jsonb,
	"track_fact" text,
	"emoji" jsonb
);
--> statement-breakpoint
ALTER TABLE "bot_prompts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "wrap_guilds" (
	"guild_id" text NOT NULL,
	"started_at" timestamp with time zone DEFAULT now(),
	"local_time" text,
	"posted" boolean,
	"wrap_up" jsonb,
	"shame" jsonb,
	"wrap_tracks" jsonb,
	"wrap_artists" jsonb,
	"interval" numeric,
	"channel" text
);
--> statement-breakpoint
ALTER TABLE "wrap_guilds" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_tracks" (
	"guild_id" text NOT NULL,
	"user_id" text NOT NULL,
	"username" text,
	"tracks" jsonb DEFAULT '[]'::jsonb,
	"top_track" text,
	"top_artist" text,
	"last_updated" timestamp with time zone,
	"artists" jsonb DEFAULT '[]'::jsonb NOT NULL
);
--> statement-breakpoint
ALTER TABLE "user_tracks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "artists" (
	"id" uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
	"legacy_id" text,
	"bandcamp" text,
	"facebook" text,
	"x" text,
	"soundcloud" text,
	"notes" text,
	"patreon" text,
	"name" text,
	"instagram" text,
	"youtube" text,
	"youtubechannel" text,
	"lcname" text,
	"soundcloudID" integer,
	"spotify" text,
	"twitch" text,
	"imdb" text,
	"musicbrainz" text,
	"wikidata" text,
	"mixcloud" text,
	"facebookID" text,
	"discogs" text,
	"tiktok" text,
	"tiktokID" text,
	"jaxsta" text,
	"famousbirthdays" text,
	"songexploder" text,
	"colorsxstudios" text,
	"bandsintown" text,
	"linktree" text,
	"onlyfans" text,
	"wikipedia" text,
	"audius" text,
	"zora" text,
	"catalog" text,
	"opensea" text,
	"foundation" text,
	"lastfm" text,
	"linkedin" text,
	"soundxyz" text,
	"mirror" text,
	"glassnode" text,
	"collectsNFTs" boolean,
	"spotifyusername" text,
	"bandcampfan" text,
	"tellie" text,
	"wallets" text[],
	"ens" text,
	"lens" text,
	"added_by" uuid,
	"cameo" text,
	"farcaster" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"supercollector" text,
	"bio" text,
	"webmapdata" jsonb,
	"node_pfp" jsonb
);
--> statement-breakpoint
ALTER TABLE "artists" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
	"email" text,
	"username" text,
	"wallet" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"legacy_id" text,
	"is_admin" boolean DEFAULT false NOT NULL,
	"is_white_listed" boolean DEFAULT false NOT NULL,
	"is_super_admin" boolean DEFAULT false NOT NULL,
	"is_hidden" boolean DEFAULT false NOT NULL,
	"accepted_ugc_count" bigint
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "ugcresearch" (
	"id" uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"artist_uri" text,
	"accepted" boolean DEFAULT false,
	"ugc_url" text,
	"site_name" text,
	"site_username" text,
	"artist_id" uuid,
	"date_processed" timestamp,
	"name" text,
	"user_id" uuid
);
--> statement-breakpoint
ALTER TABLE "ugcresearch" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "featured" (
	"id" uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
	"featured_artist" uuid,
	"featured_collector" uuid,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "featured" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "urlmap" (
	"id" uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
	"site_url" text NOT NULL,
	"site_name" text NOT NULL,
	"example" text NOT NULL,
	"app_string_format" text NOT NULL,
	"order" integer,
	"is_iframe_enabled" boolean DEFAULT false NOT NULL,
	"is_embed_enabled" boolean DEFAULT false NOT NULL,
	"card_description" text,
	"card_platform_name" text,
	"is_web3_site" boolean NOT NULL,
	"created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
	"site_image" text,
	"regex" text DEFAULT '""' NOT NULL,
	"regex_matcher" text,
	"is_monetized" boolean DEFAULT false NOT NULL,
	"regex_options" text[],
	"color_hex" text DEFAULT '#000000',
	"platform_type_list" "platform_type"[] DEFAULT '{"RAY['social'::platform_typ"}'
);
--> statement-breakpoint
ALTER TABLE "urlmap" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "artists" ADD CONSTRAINT "artists_added_by_fkey" FOREIGN KEY ("added_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ugcresearch" ADD CONSTRAINT "ugcresearch_artist_id_fkey" FOREIGN KEY ("artist_id") REFERENCES "public"."artists"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ugcresearch" ADD CONSTRAINT "ugcresearch_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "featured" ADD CONSTRAINT "featured_featured_artist_fkey" FOREIGN KEY ("featured_artist") REFERENCES "public"."artists"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "featured" ADD CONSTRAINT "featured_featured_collector_fkey" FOREIGN KEY ("featured_collector") REFERENCES "public"."artists"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_user_tracks_guild_id" ON "user_tracks" USING btree ("guild_id" text_ops);--> statement-breakpoint
CREATE INDEX "idx_user_tracks_user_id" ON "user_tracks" USING btree ("user_id" text_ops);--> statement-breakpoint
CREATE INDEX "artists_added_by_created_at_idx" ON "artists" USING btree ("added_by" timestamptz_ops,"created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "artists_lcname_btree_idx" ON "artists" USING btree ("lcname" text_ops);--> statement-breakpoint
CREATE INDEX "artists_lcname_trgm_gin" ON "artists" USING gin ("lcname" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "artists_lcname_trgm_idx" ON "artists" USING gist ("lcname" gist_trgm_ops);--> statement-breakpoint
CREATE INDEX "artists_name_trgm_idx" ON "artists" USING gist ("name" gist_trgm_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "artists_spotify_uniq" ON "artists" USING btree ("spotify" text_ops) WHERE (spotify IS NOT NULL);--> statement-breakpoint
CREATE INDEX "idx_artists_added_by" ON "artists" USING btree ("added_by" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_artists_name" ON "artists" USING btree ("name" text_ops);--> statement-breakpoint
CREATE INDEX "idx_artists_name_gin" ON "artists" USING gin (to_tsvector('english'::regconfig, name) tsvector_ops);--> statement-breakpoint
CREATE INDEX "idx_ugcresearch_user_id" ON "ugcresearch" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "ugcresearch_user_created_at_idx" ON "ugcresearch" USING btree ("user_id" timestamp_ops,"created_at" timestamp_ops);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "funfacts" AS PERMISSIVE FOR SELECT TO "mnweb" USING (true);--> statement-breakpoint
CREATE POLICY "mnweb_delete_aiprompts" ON "aiprompts" AS PERMISSIVE FOR DELETE TO "mnweb" USING (true);--> statement-breakpoint
CREATE POLICY "mnweb_insert_aiprompts" ON "aiprompts" AS PERMISSIVE FOR INSERT TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_select_aiprompts" ON "aiprompts" AS PERMISSIVE FOR SELECT TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_update_aiprompts" ON "aiprompts" AS PERMISSIVE FOR UPDATE TO "mnweb";--> statement-breakpoint
CREATE POLICY "mn_bot_history_ins" ON "history" AS PERMISSIVE FOR INSERT TO "mn_bot" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "mn_bot_history_sel" ON "history" AS PERMISSIVE FOR SELECT TO "mn_bot";--> statement-breakpoint
CREATE POLICY "mn_bot_history_upd" ON "history" AS PERMISSIVE FOR UPDATE TO "mn_bot";--> statement-breakpoint
CREATE POLICY "mn_bot_bot_prompts_sel" ON "bot_prompts" AS PERMISSIVE FOR SELECT TO "mn_bot" USING (true);--> statement-breakpoint
CREATE POLICY "mn_bot_wrap_guilds_del" ON "wrap_guilds" AS PERMISSIVE FOR DELETE TO "mn_bot" USING (true);--> statement-breakpoint
CREATE POLICY "mn_bot_wrap_guilds_ins" ON "wrap_guilds" AS PERMISSIVE FOR INSERT TO "mn_bot";--> statement-breakpoint
CREATE POLICY "mn_bot_wrap_guilds_sel" ON "wrap_guilds" AS PERMISSIVE FOR SELECT TO "mn_bot";--> statement-breakpoint
CREATE POLICY "mn_bot_wrap_guilds_upd" ON "wrap_guilds" AS PERMISSIVE FOR UPDATE TO "mn_bot";--> statement-breakpoint
CREATE POLICY "mn_bot_user_tracks_ins" ON "user_tracks" AS PERMISSIVE FOR INSERT TO "mn_bot" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "mn_bot_user_tracks_sel" ON "user_tracks" AS PERMISSIVE FOR SELECT TO "mn_bot";--> statement-breakpoint
CREATE POLICY "mn_bot_user_tracks_upd" ON "user_tracks" AS PERMISSIVE FOR UPDATE TO "mn_bot";--> statement-breakpoint
CREATE POLICY "Allow webmapdata_editor to see all rows" ON "artists" AS PERMISSIVE FOR SELECT TO "webmapdata_editor" USING (true);--> statement-breakpoint
CREATE POLICY "Allow webmapdata_editor to update webmapdata column" ON "artists" AS PERMISSIVE FOR UPDATE TO "webmapdata_editor";--> statement-breakpoint
CREATE POLICY "mnweb_delete_artists" ON "artists" AS PERMISSIVE FOR DELETE TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_insert_artists" ON "artists" AS PERMISSIVE FOR INSERT TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_select_artists" ON "artists" AS PERMISSIVE FOR SELECT TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_update_artists" ON "artists" AS PERMISSIVE FOR UPDATE TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_delete_users" ON "users" AS PERMISSIVE FOR DELETE TO "mnweb" USING (true);--> statement-breakpoint
CREATE POLICY "mnweb_insert_users" ON "users" AS PERMISSIVE FOR INSERT TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_select_users" ON "users" AS PERMISSIVE FOR SELECT TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_update_users" ON "users" AS PERMISSIVE FOR UPDATE TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_delete_ugcresearch" ON "ugcresearch" AS PERMISSIVE FOR DELETE TO "mnweb" USING (true);--> statement-breakpoint
CREATE POLICY "mnweb_insert_ugcresearch" ON "ugcresearch" AS PERMISSIVE FOR INSERT TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_select_ugcresearch" ON "ugcresearch" AS PERMISSIVE FOR SELECT TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_update_ugcresearch" ON "ugcresearch" AS PERMISSIVE FOR UPDATE TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_delete_featured" ON "featured" AS PERMISSIVE FOR DELETE TO "mnweb" USING (true);--> statement-breakpoint
CREATE POLICY "mnweb_insert_featured" ON "featured" AS PERMISSIVE FOR INSERT TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_select_featured" ON "featured" AS PERMISSIVE FOR SELECT TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_update_featured" ON "featured" AS PERMISSIVE FOR UPDATE TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_delete_urlmap" ON "urlmap" AS PERMISSIVE FOR DELETE TO "mnweb" USING (true);--> statement-breakpoint
CREATE POLICY "mnweb_insert_urlmap" ON "urlmap" AS PERMISSIVE FOR INSERT TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_select_urlmap" ON "urlmap" AS PERMISSIVE FOR SELECT TO "mnweb";--> statement-breakpoint
CREATE POLICY "mnweb_update_urlmap" ON "urlmap" AS PERMISSIVE FOR UPDATE TO "mnweb";
*/