/** @jest-environment node */
import { drizzle } from 'drizzle-orm/pglite';
import { sql, type SQL } from 'drizzle-orm';
import { readFileSync } from 'node:fs';
import * as schema from '@/server/db/schema';
jest.mock('@/server/db/drizzle', () => ({ get db() { return database; } }));
const { PGlite } = process.getBuiltinModule('module').createRequire(__filename)('@electric-sql/pglite');
const client = new PGlite();
const driver = drizzle(client, {schema});
const database = { execute: async (q: SQL) => (await driver.execute(q)).rows, transaction: (fn: any) => driver.transaction(tx => fn({execute: async (q: SQL) => (await tx.execute(q)).rows})) };
const id='00000000-0000-4000-8000-000000000001';
const other='00000000-0000-4000-8000-000000000002';
let setName: typeof import('../setUserName').setUserName;
let getLeaderboard: typeof import('../../queries/getLeaderboard').getLeaderboard;
beforeAll(async () => {
  jest.resetModules(); ({setUserName:setName}=await import('../setUserName'));
  ({getLeaderboard}=await import('../../queries/getLeaderboard'));
  await client.exec(`create table users (id uuid primary key, username text, wallet text, updated_at timestamptz default now(), email text, is_hidden boolean default false);
    create table artists (added_by uuid); create table ugcresearch (user_id uuid);`);
  await client.exec(readFileSync('drizzle/0033_user_names.sql','utf8'));
  await client.exec(`create role mnweb; grant select, insert, update on users, artists, ugcresearch to mnweb;
    alter table users enable row level security;
    create policy app_users on users to mnweb using (true) with check (true);
    set role mnweb;`);
});
afterAll(async()=>{await client.close();});
it('generates once, preserves chosen names, confirms and rejects duplicate/private names',async()=>{
 await driver.execute(sql`insert into users(id,username) values(${id},'listener@example.test'),(${other},'Chosen Name')`);
 await driver.execute(sql`insert into artists(added_by) values(${id})`);
 await driver.execute(sql`insert into ugcresearch(user_id) values(${id})`);
 const first=await setName(id);
 const account = await driver.query.users.findFirst({columns:{id:true,username:true,usernameNeedsConfirmation:true,usernamePromptedAt:true},where:(users,{eq})=>eq(users.id,id)});
 expect(account).toEqual({id,username:first.username,usernameNeedsConfirmation:true,usernamePromptedAt:null});
 expect(first.username).toMatch(/^\S+ \S+$/);expect(first.usernameNeedsConfirmation).toBe(true);
 expect((await setName(id)).username).toBe(first.username);
 expect((await getLeaderboard())[0].username).toBe(first.username);
 expect((await setName(other)).username).toBe('Chosen Name');
 await expect(setName(id,' chosen name ')).rejects.toThrow('already taken');
 await expect(setName(id,'private@example.test')).rejects.toThrow('email');
 const confirmed=await setName(id,first.username);
 expect(confirmed.usernameNeedsConfirmation).toBe(false);
 expect((await setName(id,'New Name')).username).toBe('New Name');
 await expect(driver.execute(sql`update users set username='NEW NAME' where id=${other}`)).rejects.toThrow();
 const shown = await driver.execute(sql`update users set username_prompted_at=now() where id=${id} and username_prompted_at is null returning id`);
 const repeated = await driver.execute(sql`update users set username_prompted_at=now() where id=${id} and username_prompted_at is null returning id`);
 expect(shown.rows).toHaveLength(1); expect(repeated.rows).toHaveLength(0);
 const credits=await getLeaderboard();
 expect(credits).toEqual([expect.objectContaining({userId:id,username:'New Name',artistsCount:1,ugcCount:1})]);
});
