// Mock wagmi module
const mockWagmi = {
  useAccount: jest.fn(() => ({ isConnected: false, address: undefined })),
  useConnect: jest.fn(() => ({ connect: jest.fn() })),
  useDisconnect: jest.fn(() => ({ disconnect: jest.fn() })),
  useConfig: jest.fn(() => ({})),
  usePublicClient: jest.fn(() => ({})),
  useWalletClient: jest.fn(() => ({})),
  useBalance: jest.fn(() => ({ data: null })),
  useEnsName: jest.fn(() => ({ data: null })),
  useEnsAvatar: jest.fn(() => ({ data: null })),
  useNetwork: jest.fn(() => ({ chain: null })),
  useSwitchNetwork: jest.fn(() => ({ switchNetwork: jest.fn() })),
  useWaitForTransaction: jest.fn(() => ({ data: null })),
  useContractRead: jest.fn(() => ({ data: null })),
  useContractWrite: jest.fn(() => ({ write: jest.fn() })),
  usePrepareContractWrite: jest.fn(() => ({ config: null })),
  useSignMessage: jest.fn(() => ({ signMessage: jest.fn() })),
  useSignTypedData: jest.fn(() => ({ signTypedData: jest.fn() })),
  createConfig: jest.fn(() => ({})),
  getAccount: jest.fn(() => ({})),
  getPublicClient: jest.fn(() => ({})),
  getWalletClient: jest.fn(() => ({})),
  getBalance: jest.fn(() => Promise.resolve({ value: 0n })),
  getEnsName: jest.fn(() => Promise.resolve(null)),
  getEnsAvatar: jest.fn(() => Promise.resolve(null)),
  readContract: jest.fn(() => Promise.resolve(null)),
  writeContract: jest.fn(() => Promise.resolve({ hash: '0x' })),
  sendTransaction: jest.fn(() => Promise.resolve({ hash: '0x' })),
  signMessage: jest.fn(() => Promise.resolve('0x')),
  signTypedData: jest.fn(() => Promise.resolve('0x')),
  verifyMessage: jest.fn(() => Promise.resolve({})),
  verifyTypedData: jest.fn(() => Promise.resolve({})),
  watchAccount: jest.fn(() => () => {}),
  watchPublicClient: jest.fn(() => () => {}),
  watchWalletClient: jest.fn(() => () => {}),
  watchBalance: jest.fn(() => () => {}),
  watchEnsName: jest.fn(() => () => {}),
  watchEnsAvatar: jest.fn(() => () => {}),
  watchContractEvent: jest.fn(() => () => {}),
  watchPendingTransactions: jest.fn(() => () => {}),
  watchBlockNumber: jest.fn(() => () => {}),
  watchBlocks: jest.fn(() => () => {}),
  // Add any other wagmi exports that might be used
};

module.exports = mockWagmi;
