import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import SuggestedLinkReview from '../SuggestedLinkReview';
import {EditModeContext} from '@/app/_components/EditModeContext';
const item={id:'suggestion-1',kind:'ugc',url:'https://music.apple.com/us/artist/pete/1513734272',title:'Apple Music profile',platform:'apple_music',status:'pending',submittedAt:'2026-10-08T18:15:00Z',suggestedBy:{id:'user-1',name:'Example contributor'},origin:'submission',reviewedAt:null,reviewedBy:null};
const refresh=jest.fn();
beforeEach(()=>{jest.clearAllMocks();global.fetch=jest.fn().mockResolvedValue({ok:true,json:async()=>({items:[item],hasMore:false})});});
function mount(){return render(<EditModeContext.Provider value={{canEdit:true,isEditing:true,toggle:jest.fn(),refreshProfile:refresh}}><SuggestedLinkReview artistId="artist-1"/></EditModeContext.Provider>);}
it('credits the actual contributor and displays a timestamp before reviewing',async()=>{mount();expect(await screen.findByText('Example contributor')).toBeInTheDocument();await waitFor(()=>expect(document.querySelector('time')).toHaveAttribute('datetime',item.submittedAt));expect(screen.getByRole('button',{name:'Add to Links'})).toBeInTheDocument();});
it('posts only the decision and identity of the suggestion, then reloads persisted reviewer attribution',async()=>{
 (fetch as jest.Mock).mockResolvedValueOnce({ok:true,json:async()=>({items:[item],hasMore:false})}).mockResolvedValueOnce({ok:true,json:async()=>({success:true})}).mockResolvedValueOnce({ok:true,json:async()=>({items:[{...item,status:'approved',reviewedAt:'2026-10-08T18:20:00Z',reviewedBy:{id:'owner',name:'Pete'}}],hasMore:false})});mount();fireEvent.click(await screen.findByRole('button',{name:'Add to Links'}));await waitFor(()=>expect(refresh).toHaveBeenCalled());expect(JSON.parse((fetch as jest.Mock).mock.calls[1][1].body)).toEqual({id:item.id,kind:'ugc',decision:'approve'});fireEvent.click(await screen.findByText('Recently reviewed (1)'));expect(screen.getByText('Pete')).toBeInTheDocument();expect(screen.getByText('Example contributor')).toBeInTheDocument();});
it('shows a conflict without pretending approval succeeded',async()=>{(fetch as jest.Mock).mockResolvedValueOnce({ok:true,json:async()=>({items:[item],hasMore:false})}).mockResolvedValueOnce({ok:false,json:async()=>({error:'Remove the existing account first.'})});mount();fireEvent.click(await screen.findByRole('button',{name:'Add to Links'}));expect(await screen.findByRole('alert')).toHaveTextContent('Remove the existing account first.');expect(refresh).not.toHaveBeenCalled();});
it('can reach suggestions beyond a page containing only unrelated sources',async()=>{
 (fetch as jest.Mock).mockResolvedValueOnce({ok:true,json:async()=>({items:[],hasMore:true,nextOffset:100})}).mockResolvedValueOnce({ok:true,json:async()=>({items:[item],hasMore:false,nextOffset:null})});mount();fireEvent.click(await screen.findByRole('button',{name:'Load more'}));expect(await screen.findByText('Example contributor')).toBeInTheDocument();expect(fetch).toHaveBeenLastCalledWith('/api/artist/artist-1/link-suggestions?offset=100',expect.objectContaining({cache:'no-store'}));expect(screen.queryByRole('button',{name:'Load more'})).not.toBeInTheDocument();
});
it('restores a removed icon through an explicit server decision',async()=>{
 (fetch as jest.Mock).mockResolvedValueOnce({ok:true,json:async()=>({items:[{...item,kind:'source',status:'approved',hidden:true}],nextOffset:null})});mount();fireEvent.click(await screen.findByText('Recently reviewed (1)'));fireEvent.click(screen.getByRole('button',{name:'Restore link'}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith('/api/artist/artist-1/link-suggestions',expect.objectContaining({method:'POST',body:JSON.stringify({id:item.id,kind:'source',decision:'restore'})})));
});
